#! /bin/sh

pkill -f polybar
sxhkd &
polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          40
bspc config bottom_padding       20
bspc config left_padding         25
bspc config right_padding        25

# source the colors.

#bspc rule -a Yad desktop='^1' state=floating follow=on
#bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mytask state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Chromium desktop='^2' follow=on focus=on
bspc rule -a code desktop='^3' follow=on focus=on

feh --no-fehbg --bg-scale --recursive --randomize $HOME/.wallpapers/
picom --config $HOME/.config/picom/picom.conf &

bspc config normal_border_color "#1A1B26"
bspc config active_border_color "#f7768e"
bspc config focused_border_color "#414868"
bspc config presel_border_color "#73daca"

bspc config focus_follows_pointer true

xss-lock -l ~/Documents/scripts/transfer-sleep-lock-generic-delay.sh

xsetroot -cursor_name left_ptr
