#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "Usage: komorebi [start|stop]"
	exit 1
fi

if [ "$1" = 'stop' ]; then
	komorebic.exe stop &> /dev/null
	taskkill.exe /IM whkd.exe /F &> /dev/null
	exit 0
fi

if [ "$1" = 'start' ]; then
	cd /mnt/c/Users/Dani/Desktop/config/
	tasklist.exe | grep komorebi &> /dev/null
	if [ ! $? -eq 0 ]; then
		komorebic.exe start -c ./komorebi.json &> /dev/null
	fi
	tasklist.exe | grep whkd &> /dev/null
	if [ ! $? -eq 0 ]; then
		(whkd.exe -c ./whkdrc & disown) &> /dev/null
	fi
fi

